### ISSUE TITLE
Ambiguity from other repository

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [i40-Tools/AutomationMLOntology#1]
Hi everyone!

there seems to be two repositories containing an AutomationMLOntology

https://github.com/i40-Tools/vocabularies/tree/master/AutomationML

as well as this one.

Is this double publishing necessary? Thanks for clarifying!

best

Georg

**Comment by igrangel** [comment]
Hi, Georg, thanks for pointing this out. I already removed the duplicated one and this will be the used one for the further development of this ontology.
